config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts

  post "posts/:id/like" => "posts#like", as: :like_post

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :text, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.likes = 0

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js   {}
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    @post = Post.find(params[:id])
    @post.likes += 1
    @post.save

    respond_to do |format|
      format.js   {}
      format.json { render json: @post, status: :created, location: @post }
    end
  end

  private
    def post_params
      params.require(:post).permit(:text, :likes)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RemoteTrue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= post.text %>
  </td>
  <td>
    <%= link_to image_tag('yeti.jpg', width:"30", height:"30"), like_post_path(post), method: :post, remote: true %>
  </td>
  <td id="like-<%= post.id %>">
    <%= post.likes %>
  </td>
</tr>

app/views/posts/create.js.erb
$("<%= escape_javascript(render @post) %>").appendTo("#posts");

app/views/posts/index.html.erb
<br/>

<%= form_for(@post, remote: true, html:{class:"form-horizontal"}) do |f| %>

<div class="form-group row">
  <%= f.label "Write a Post", :class => "control-label col-md-2" %>
  <div class="form-controls col-md-4">
    <%= f.text_field :text, :class => 'form-control' %>
  </div>
</div>

<div class="form-group row">
  <div class="col-md-offset-2 col-md-4">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
</div>

<% end %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Post</th>
      <th>Yeti?</th>
      <th># Yeti</th>
    </tr>
  </thead>

  <tbody id="posts">
    <%= render @posts %>
  </tbody>
</table>

app/views/posts/like.js.erb
$("#like-<%= @post.id %>").text("<%= @post.likes %>");